refclock SHM 0 refid GPS precision 1e-1 offset 0.200 delay 0.200 poll 4 noselect
refclock PPS /dev/pps0 refid GPPS lock GPS poll 4
refclock PPS /dev/pps1 refid RB lock GPS prefer trust poll 4 offset 0.296745

pool 2.debian.pool.ntp.org iburst maxsources 2

driftfile /var/lib/chrony/chrony.drift
maxupdateskew 100.0
makestep 1 3
rtcsync

leapseclist /usr/share/zoneinfo/leap-seconds.list

allow 10.0.0.0/24
allow 10.0.118.0/24
allow 192.168.1.0/24
allow 10.0.113.0/24
allow 192.168.7.0/24

keyfile /etc/chrony/chrony.keys
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony
